### ISSUE TITLE
Markdown will not be processed

### ISSUE THREAD

**Issue by ghost** [MarcelKr/grav-theme-tail#12]
Hey there. Thanks for that beautiful theme.

When using the Blog page (template set als `post-list`) and adding a sub-page as `post`, the outcome will not be rendered as markdown.
I have seen this issue came up before, but I checked the version and also all my settings. I am not sure, what particularly I am doing wrong.
![Bildschirmfoto 2021-07-26 um 20 39 19](https://user-images.githubusercontent.com/57176067/127041731-59367a81-9570-4869-9d6c-1ee362fbb993.png)
![Bildschirmfoto 2021-07-26 um 20 39 27](https://user-images.githubusercontent.com/57176067/127041734-2bcda6a1-281b-4115-a41d-b3abdf79ab2e.png)
![Bildschirmfoto 2021-07-26 um 20 39 33](https://user-images.githubusercontent.com/57176067/127041735-6b5f03fc-e2e6-4235-bc92-2377419e9070.png)

**Comment by MarcelKr** [comment]
Hey @timbuening, thanks for reporting the issue. It seems the stricter template processing introduced in some recent version of grav breaks the rendering. I'll look into that.

For now it can be fixed using the following options in `system.yaml`. But please only use them temporarily for security reasons.
```yaml
strict_mode:
  twig_compat: true                            # Set to true to enable deprecated Twig settings (autoescape: false)

twig:
  autoescape: false                               # Autoescape Twig vars (DEPRECATED, always enabled in strict mode)
```
