### ISSUE TITLE
How do I use the templates?

### ISSUE THREAD

**Issue by FunDeckHermit** [MarcelKr/grav-theme-tail#7]
Hello,

I'm sure its just a stupid mistake from my end but I can't seem te recreate the example image.

I've installed and activated your plugin and created this: 
![image](https://user-images.githubusercontent.com/5075692/77936344-0f528480-72b3-11ea-9608-929d0d51c3f4.png)

I've added a title and content to the post. 
![image](https://user-images.githubusercontent.com/5075692/77936600-66f0f000-72b3-11ea-9942-15c5f381bf78.png)

Why does the main event page stays empty?

**Comment by MarcelKr** [comment]
Hey, I can confirm that this isn't working properly. I'm investigating. Thanks for reporting :)

**Comment by FunDeckHermit** [comment]
If you want to look around for yourself in my instance just say so.

**Comment by MarcelKr** [comment]
Can you put a header like the following in the post-list. The post list is based on a collection and collections need to have a 'definition' like below.

I don't know whether to change the behavior since it allows for sorting and define the pagination parameters.

```
---
content:
    items: '@self.children'
    order:
        by: date
        dir: desc
    limit: 10
    pagination: true
---
```
